version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: app_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: secret
      JWT_SECRET: supersecretJWTkey
      JWT_EXPIRES_IN: 3600s
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
